name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*'   # 例如 v1.2.3

permissions:
  contents: write     # 创建 GitHub Release
  id-token: write     # 允许 npm provenance (npm publish --provenance)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: npm test --if-present

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true